[package]
name = "yolk"
authors = ["ElKowar <dev@elkowar.dev>"]
description = "Templated dotfile management without template files"
version = "0.0.6"
edition = "2021"
repository = "https://github.com/elkowar/yolk"
homepage = "https://elkowar.github.io/yolk"

[package.metadata.wix]
upgrade-guid = "04CA81A1-EF78-4B08-8D76-74A8DB52A323"
path-guid = "0EBEA995-6928-4AE1-99B4-EF89713778B1"
license = false
eula = false

[dependencies]
assert_fs = "1.1.2"
assert_matches = "1.5.0"
cached = "0.54.0"
clap = { version = "4.5.21", features = ["derive", "env"] }
dirs = "5.0.1"
dunce = "1.0.5"
extend = "1.2.0"
fs-err = "3.0.0"
indoc = "2.0.5"
miette = { version = "7.4.0", features = ["fancy"] }
mlua = { version = "0.10.1", features = [
    "luau",
    # "lua52",
    # "vendored",
    "error-send",
    "anyhow",
    "send",
] }
pest_derive = { version = "2.7.14", features = ["grammar-extras"] }
predicates = "3.1.2"
regex = "1.11.1"
testresult = "0.4.1"
thiserror = "2.0.3"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
walkdir = "2.5.0"
which = "7.0.0"
whoami = "1.5.2"
winnow = { version = "0.6.20", features = ["unstable-recover"] }

# The profile that 'cargo dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"

# [workspace.metadata.dist.dependencies.apt]
# "musl-tools" = "*"
