[package]
name = "yolk"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
indoc = "2.0.5"
pest = { version = "2.7.14" }
pest_derive = { version = "2.7.14", features = ["grammar-extras"] }
regex = "1.11.1"
rhai = "1.20.0"
tempdir = "0.3.7"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
