[package]
name = "yolk"
authors = ["ElKowar <dev@elkowar.dev>"]
description = "Templated dotfile management without template files"
version = "0.0.5"
edition = "2021"
repository = "https://github.com/elkowar/yolk"
homepage = "https://elkowar.github.io/yolk"

[dependencies]
assert_fs = "1.1.2"
cached = "0.54.0"
clap = { version = "4.5.21", features = ["derive", "env"] }
dirs = "5.0.1"
dunce = "1.0.5"
extend = "1.2.0"
fs-err = "3.0.0"
indoc = "2.0.5"
miette = { version = "7.4.0", features = ["fancy"] }
rhai = { version = "1.20.0", features = ["std", "sync"] }
pest = { version = "2.7.14" }
pest_derive = { version = "2.7.14", features = ["grammar-extras"] }
predicates = "3.1.2"
regex = "1.11.1"
testresult = "0.4.1"
thiserror = "2.0.3"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
walkdir = "2.5.0"
which = "7.0.0"
whoami = "1.5.2"

# The profile that 'cargo dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"

# [workspace.metadata.dist.dependencies.apt]
# "musl-tools" = "*"
