[package]
name = "yolk"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
assert_fs = "1.1.2"
clap = { version = "4.5.21", features = ["derive", "env"] }
dirs = "5.0.1"
fs-err = "3.0.0"
indoc = "2.0.5"
pest = { version = "2.7.14" }
pest_derive = { version = "2.7.14", features = ["grammar-extras"] }
predicates = "3.1.2"
regex = "1.11.1"
rhai = { version = "1.20.0", features = ["sync"] }
testresult = "0.4.1"
# tracing = "0.1.40"
# tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
walkdir = "2.5.0"
