[workspace]
members = ["cargo:."]

[dist]
github-build-setup = "dist-custom.yml"
cargo-dist-version = "0.26.0-prerelease.3"
pr-run-mode = "upload"
ci = "github"
installers = ["shell"]
targets = [
    # "aarch64-apple-darwin",
    # "x86_64-apple-darwin",
    "x86_64-unknown-linux-gnu",
    # "x86_64-pc-windows-msvc",
]
install-path = "CARGO_HOME"
install-updater = true

[[dist.extra-artifacts]]
artifacts = ["docs/book/book-man/book.man"]
build = ["mdbook", "build"]
