[workspace]
members = ["cargo:."]

[dist]
global-artifacts-jobs = ["./build-man"]
# github-build-setup = "build-setup.yml"
cargo-dist-version = "0.26.1"
# pr-run-mode = "upload"
pr-run-mode = "plan"
ci = "github"
installers = ["shell", "homebrew"]
tap = "elkowar/homebrew-tap"
publish-jobs = ["homebrew"]
formula = "yolk"
targets = [
    # "aarch64-apple-darwin",
    "x86_64-apple-darwin",
    "x86_64-unknown-linux-gnu",
    # "x86_64-pc-windows-msvc",
]
install-path = "CARGO_HOME"
install-updater = false

# include = ["yolk.man"]
