name: check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_call: {}
env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy,rustfmt
      - name: Install nextest
        uses: taiki-e/install-action@nextest
      - name: Load rust cache
        uses: Swatinem/rust-cache@v2

      - name: Setup problem matchers
        uses: r7kamura/rust-problem-matchers@v1

      - name: Check formatting
        run: cargo fmt -- --check
      - name: Cargo check
        run: cargo check
      - name: Run tests
        run: cargo nextest run
