name: Check

on:
  push:
    tags-ignore:
      - "v*.*.*"
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
    tags-ignore:
      - "v*.*.*"
  workflow_call: {}
env:
  CARGO_TERM_COLOR: always

jobs:
  mdbook-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install cargo-binstall
        uses: cargo-bins/cargo-binstall@v1.10.16
      - name: Install mdbook, mdbook-linkcheck
        run: cargo binstall mdbook mdbook-linkcheck
      - name: mdbook linkcheck
        run: |
          echo '[output.linkcheck]' > docs/book.toml
          mdbook build docs

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy,rustfmt
      - uses: rui314/setup-mold@v1
        name: Setup mold
      - name: Install nextest
        uses: taiki-e/install-action@nextest
      - name: Load rust cache
        uses: Swatinem/rust-cache@v2

      - name: Setup problem matchers
        uses: r7kamura/rust-problem-matchers@v1

      - name: Check formatting
        run: cargo fmt -- --check
      - name: Cargo check
        run: cargo check
      - name: Run tests
        run: |
          cargo build
          cargo nextest run
