name: release

on:
  push:
    tags:
      - "v*.*.*"

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    uses: ./.github/workflows/check.yml
  build:
    strategy:
      matrix:
        target:
          - name: linux
            os: ubuntu-latest
            target: x86_64-unknown-linux-musl
          # - name: windows
          #   os: windows-latest
          #   target: x86_64-pc-windows-msvc
          # - name: macos-x86_64
          #   os: macos-latest
          #   target: x86_64-apple-darwin
          # - name: macos-arm
          #   os: macos-latest
          #   target: aarch64-apple-darwin
    runs-on: ${{ matrix.target.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target.target }}
      - name: Load rust cache
        uses: Swatinem/rust-cache@v2
      - name: Setup problem matchers
        uses: r7kamura/rust-problem-matchers@v1

      - name: build release binary
        run: cargo build --release

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: yolk-${{ matrix.target.name }}
          path: ./target/${{ matrix.target.target }}/release/yolk

  release:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    steps:
      - name: Create a Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "yolk-*"
          name: Yolk ${{ github.ref_name }}
          tag: ${{ github.ref_name }}
